Added dry-run option to prepare-release command
yaclt/yaclt pull request #190
Opened 2022-07-26 03:32 UTC by mitchellss

Resolves: #128 

## How to Test

1. Run ```yactl new -m "<your message here>"```
2. Run the command ```yactl prepare-release --dry-run``` from the master branch of a git project
3. Verify that CHANGELOG.md is unchanged and that the change preview contains the earlier added change
4. Run ```yactl prepare-release --dry-run --quiet``` and verify a contradiction error is printed

## Potential Side Effects/Things to Look Out For

Kebab-case option differs from the rest of the camel-cased options which required a slight workaround in the validate-argv-middleware.

2022-07-26 11:12 UTC, mrjones2014 requested changes
Been a while since I worked on this project, I forgot the rest of the options are `camelCase` -- not sure why I did it that way but let's make `--dryRun` camelCase so it's consistent with the others.

2022-07-26 11:12 UTC, mrjones2014 commented on docs/COMMANDS.md
> +| `--dry-run`              |       | Print out changes to be made without writing them.
I had forgotten the rest of the options were `camelCase` -- let's make this one follow suit for consistency.

2022-07-26 21:40 UTC, mitchellss commented on docs/COMMANDS.md
> +| `--dry-run`              |       | Print out changes to be made without writing them.
Makes sense. It should be all fixed now.

2022-07-27 11:10 UTC, mrjones2014 approved these changes
looks good to me

2022-07-27 11:11 UTC, merged